language: objective-c
osx_image: xcode11.2
before_install:
- pod repo update
pods: rm -rf Pods bundle install bundle exec pod install
script:
- set -o pipefail && xcodebuild -workspace Tsukuba-iOS.xcworkspace -scheme Tsukuba-iOS
  -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO | xcpretty -c
notifications:
  slack:
    rooms:
      - mushare:ud3NGjCX5VT1OiJ8FmT0UlmZ#tsukuba
    secure: ksGMQxId1Y5WSGCp1cKCWZFe6de3gwOqfKBtbo4wqBnjez0q+a5Cuc3Hr3yIqIyOLGNqbRDmaOE8CpL4aR4skvsKGNdlhd5BjWJ9D6negt8LQjzzXQabi+iO8lNbYbeoJBp2il3HEWE68GutMEA/eI4+Jok3FvwMmC5MLrH1LTmQissjzTV21uEmVIry3vQr+/jtUokwtHG7PgIMTocKXXg2FJFDB0ZHV4Hbw21iGmN/eCFY5oz6LUIU0R/QaJpsOdhEhUtFLPI+qrKZskqj2hxb4X9UodwjkuD7D/MI/giNi6nL0dTNh9xpPBqCM1Ky0YOrRXqVtPmTKoaKoKFSodB7beHXkA8mnLvpfpZKAknMYLHiKAK+0Wcw87nHqoBcZ5sSFtrFZ3NDBcnTJFhV7nbS11g/A4tstylyzd1HpVyLkanUJrujI1/+2RJJF1oIIOb5rllNqj6jf5JK2s3r9WKu2x3Sf0/Uecf53xvW6OXUZTb4nQYjBS1AMaKymX7wGBUzcRICQMBrU//xdbPLYK7LfwWYl+hxINrlI+P796s4bxoP9Y7Qffju1dVbW+0/vBoV0rCbut1+fq4DUGJrJigyG34ZJzzdjMu/m/JM8nSr0CoKfky8ooGScQdUY2nHidGbWxJTyv00Gla0ddv8FFCSE+F3ZPI4fwdkSW4p6t8=
